### ISSUE TITLE
Inquiry About Licensing Options for Triplecyber

### ISSUE THREAD

**Issue by Riki1200** [tigase/tigase-server#221]
Dear Tigase Team,

My name is Romeo, and I am a developer with Triplecyber. We are currently exploring various solutions to enhance our infrastructure and are very interested in your products.

Could you please provide us with detailed information about the different licensing options available? We are particularly interested in understanding any flexible licensing terms that might be suitable for a business of our size and nature.

Additionally, if there are other special arrangements or enterprise-specific licenses, we would be keen to learn about those as well.

Thank you for your assistance, and I look forward to your prompt response.

Best regards,

Romeo
Developer, Triplecyber

**Comment by arturhefczyc** [comment]
Hi,

Thank you for contacting us with your questions and interest in using Tigase software for your project. 

You can find basic pricing information and licencing options on our website: https://tigase.net/pricing-xmpp

However, we are flexible with licensing options and if you have specific needs we would be happy to discuss details with you to find best solution for your case.

Please do not hesitate to contact us directly, rather than through the github website. You can use the contact form on the website:  https://tigase.net/contact-sales

Or send us an email directly to sales at tigase.net.

**Comment by Riki1200** [comment]
Hello,

Thank you very much for the information and for offering flexible licensing options. We appreciate your willingness to discuss a licensing solution that best fits our needs.

We are particularly interested in exploring the possibility of using a licensing type similar to the MIT License for our project. We believe that such a licensing arrangement would align well with our project’s requirements and distribution plans.

Could we possibly discuss this further? I am looking forward to your thoughts on whether an MIT-like license could be an option for us.

Thank you once again for your support and assistance.

Best regards,

Romeo
Developer, Triplecyber
