### ISSUE TITLE
How to enable the module of jingle?

### ISSUE THREAD

**Issue by godpit** [tigase/tigase-server#25]
How to enable the module of jingle?

the config.tdsl:

```
'sess-man' () {
     'http://jabber.org/protocol/jingle' () {}
}
```

It did not work,  the client  received an unsupported features error about jingle.

**Comment by woj-tek** [comment]
Jingle is inherently client-side protocol, and as explained in https://github.com/tigase/stork/issues/25 is used only for "signaling". Having this in mind, enabling server plugin won't suddenly make Jingle "available" because it depends on what other client supports.

Said plugin in Tigase will only facilitate dedicated threads to process Jingle packets.
